import { PokemonType } from "./type";

export interface Move {
  id: number;
  name_ja: string;
  name_en: string;
  type: PokemonType;
  accuracy: number;
  power: number;
  damage_class_number: number;
  is_renzoku: boolean;
  min_renzoku: number;
  max_renzoku: number;
  is_freeze_dry: boolean;
  is_hydro_steam: boolean;
  is_psy_blade: boolean;
  is_zidanda: boolean;
  is_punch: boolean;
  is_kiru: boolean;
  is_tama: boolean;
  is_hadou: boolean;
  is_kamituki: boolean;
  is_kaze: boolean;
  is_odori: boolean;
  is_oto: boolean;
  is_triple_kick_accelerator: boolean;
  is_sutemi_waza: boolean;
  is_heavy_slam: boolean;
  is_ketaguri: boolean;
  is_hatakiotosu: boolean;
  is_kishikaisei: boolean;
  is_karagenki: boolean;
  is_shiohuki: boolean;
  is_weather_ball: boolean;
  is_2x_under_condition: boolean;
  is_wring_out: boolean;
  is_stored_power: boolean;
  is_psyshock: boolean;
  is_electro_ball: boolean;
  is_body_press: boolean;
  is_ikasama: boolean;
  is_through_rank: boolean;
  is_ohakamairi: boolean;
  is_kakutei_critical: boolean;
  is_type_changeable: boolean;
  is_flying_press: boolean;
  is_zishin: boolean;
  is_katayaburi: boolean;
  is_wide_force: boolean;
  is_mist_burst: boolean;
  is_rising_bolt: boolean;
  is_waves_of_the_earth: boolean;
  is_kabehakai: boolean;
  is_batugun_sugoi: boolean;
  is_hundo: boolean;
  is_tutakon: boolean;
}
export const MOVE_DAMAGE_CLASS_STATUS = 1;
export const MOVE_DAMAGE_CLASS_PHYSICAL = 2;
export const MOVE_DAMAGE_CLASS_SPECIAL = 3;
